GROQ_API_KEY = "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"



MAILERLITE_API_KEY = "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiI0IiwianRpIjoiNTU0YjBjNzBkNWE4NTAzODliNzI4MTkxMjFkYTE3ZDY3ZmI3NGI3YjFhZjFkNDBhNmM3YjdkMTNhY2EzMDk5Yzg1YjA5Y2JjY2UwZTVhN2YiLCJpYXQiOjE3NDg2MDk0NjIuNzYxOCwibmJmIjoxNzQ4NjA5NDYyLjc2MTgwMiwiZXhwIjo0OTA0MjgzMDYyLjc1ODM0MSwic3ViIjoiMTU2OTUwOSIsInNjb3BlcyI6W119.s1JbP27NE0R7brrrtQDmbJRtMm4pXCQQ_ewhQtcA4YA6qkXPVlhV6_vtorirktiPF7PbhxM0hdB_0d-OOKrcoHF1zXcpT2v2uEH8xPqGFKpN-2yIb8H4XureTikSclsiya4_XUOuICYkmwgllHhSilmXeL4vFwweOrNSZ8cEePO2vYwKUhIbrgWWVz2VaUkA_uJ8BCjVagIVQCk3B2GoRLD4eQCor59-xX9dpsyv8h8OlutxZucaTTvvi45jYsGu_e_rpI_4ztK5Mw9oaQY75d2FoycOqJ_F3vydWa4Zpp74WHz2mkvEXxslsuaaG7puH4TQlBRiIrkOoAMjdzDYPin_taU3rhjJFqMLbcqOmkCK8C_nburSAh0bjhwcQgxW8DOsu7bH6vACCjQZai2RoHwdI72aIlbPKyLpvSi_AklTr9HtJKRtKN7qUiG8dnZztemUn3vT2fmVOOOmJiaI6wVM464baJS6axFw5aHR-e2rn06eD11Ct0sSHhk5h9-_Q6skd8fzzwvhrQ4yk01N4eiWbuU96HYPs00-pluPns38Sj8CH7A49tjrT5lnqs31bqZslZSsLqAOj-HH6hjMnMu_dsjc7yEiWhSJn3jPeormZ5qImqhGNZCoGzsG24AyT3CMZRWk7PnqgFgo8Xuj8JBA4F8sx3THqLe_j8ReiFE"

MAILERLITE_GROUP_ID = "155828431764850428"



GOOGLE_SHEETS_WEBHOOK_URL = "https://script.google.com/macros/s/AKfycbxLgHWFOK-d-V6fYOqFDUg8ETnaLMci1h1CYL0oGD2KNTHJ3hPe9DdPJxq4GNpyeDE/exec"
